using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Newtonsoft.Json;
using Vulcan.Core.DataAccess.Validations;

namespace Vulcan.Core.DataAccess.Models
{
    public class Field
    {
        public int Id { get; set; }
        [Required]
        [MaxLength(64)]
        [JsonIgnore]
        public string TableName { get; set; }
        [Required]
        [MaxLength(64)]
        [RegularExpression("^[a-zA-Z][a-zA-Z0-9]*$", ErrorMessage = "Name contains invalid characters")]
        public string Name { get; set; }
        [Required]
        [MaxLength(64)]
        public string Title { get; set; }
        [Required]
        //[MaxLength(64)]
        public FieldType Type { get; set; }
        public bool IsHidden { get; set; }
        public bool IsDeleted { get; set; }
        [JsonIgnore]
        public bool IsSystem { get; set; }
        public bool IsAutoGenerated { get; set; }
        private List<FieldValidation> _validations;
        [JsonIgnore]
        public List<FieldValidation> Validations
        {
            get
            {
                return _validations ??
                       (_validations =
                           _validators?.Select(v => new FieldValidation(v)).ToList());
            }
            set
            {
                _validations = value;
                _validators = value.Select(v => v.Validator).ToList();
            }
        }

        private List<IValidator> _validators;
        [JsonProperty("Validations")]
        public List<IValidator> Validators
        {
            get
            {
                return _validators ??
                       (_validators =
                           Validations?.Select(v => v.Validator).ToList());
            }
            set
            {
                _validators = value;
                _validations = value.Select(v => new FieldValidation(v)).ToList();
            }
        }
        public bool ShowInUi { get; set; }
        public int UiIndex { get; set; }
        public List<FieldChoice> Choices { get; set; }

    }
}
