CREATE PROCEDURE [core].[base_Field_Update]
	@Id int,
	--@TableName varchar(64),
	--@Name varchar(64),
	@Title varchar(64),
	--@Type varchar(64),
	@IsHidden bit,
	@IsDeleted bit,
	@IsSystem bit,
	@IsAutoGenerated bit,
	@ShowInUi bit = 1,
	@UiIndex int = 0
AS
BEGIN
	UPDATE [Fields] SET 
		--[TableName]=@TableName,
		--[Name]=@Name,
		[Title]=@Title,
		--[Type]=@Type,
		[IsHidden]=@IsHidden,
		[IsDeleted]=@IsDeleted,
		[IsSystem]=@IsSystem,
		[IsAutoGenerated]=@IsAutoGenerated,
		[ShowInUi]=@ShowInUi,
		[UiIndex]=@UiIndex
	WHERE [Id]=@Id

	SELECT @Id
END
