CREATE PROCEDURE [core].[base_Migration_MigrateTable]
	@TableName varchar(64)
AS
BEGIN

	declare @CreateTableSql nvarchar(max)
	
	set @CreateTableSql = N'CREATE TABLE ' + @TableName + ' ( [Id] INT NOT NULL PRIMARY KEY identity(1,1) )'
	EXECUTE sp_executesql @CreateTableSql

	INSERT INTO [core].[Fields] ([TableName], [Name], [Title], [Type], [IsHidden], [IsDeleted], [IsSystem], [IsAutoGenerated]) 
	VALUES (@TableName, N'Id', N'Id', 2, 0, 0, 1, 1)
	
END
