CREATE PROCEDURE [core].[base_Field_Get]
AS
	SELECT [Id]
      ,[TableName]
      ,[Name]
      ,[Title]
      ,[Type]
      ,[IsHidden]
      ,[IsDeleted]
      ,[IsSystem]
      -- ,[InternalName]
	  ,[IsAutoGenerated],[ShowInUi],[UiIndex]
  FROM [Fields]
  WHERE [IsDeleted]=0 and [IsHidden]=0
