 //1
 //0
 //149
 //64
 //9/30/2016 7:33:06 AM
 // 
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 


using System.Reflection;
  
[assembly: AssemblyFileVersion("1.0.149.64")]
namespace Vulcan.Core
{
	public static class ApplicationVersion
	{
		public static int BuildDate { get; } = 20160930;
        public static string AssemblyFileVersion { get; } = "1.0.149.64";
        public static int BuildNumber { get; } = 64;
	}
}
