 //1
 //0
 //167
 //68
 //10/18/2016 1:32:06 PM
 // 
 // This code was generated by a tool. Any changes made manually will be lost
 // the next time this code is regenerated.
 // 


using System.Reflection;
  
[assembly: AssemblyFileVersion("1.0.167.68")]
namespace Vulcan.Core
{
	public static class ApplicationVersion
	{
		public static int BuildDate { get; } = 20161018;
        public static string AssemblyFileVersion { get; } = "1.0.167.68";
        public static int BuildNumber { get; } = 68;
	}
}
