CREATE TABLE [auth].[ApiUsers]
(
	[Id] INT NOT NULL identity(100000, 1),
	[Username] varchar(2048) not null,
	[PasswordHash] varchar(max) null,
	[PasswordSalt] varchar(max) null,
	[TokenExpireTimeMinutes] int null,
	[CreatedByUserId] int null,
	[CreatedByClientId] int null,
	[CreatedDate] as getdate(),
	[UpdatedByUserId] int null,
	[UpdatedByClientId] int null,
	[UpdatedDate] datetime null,
	[IsDeleted] bit not null default(0),
	[Type] int not null default(0),
	[ExternalRefId] int null,
	[SystemId] bigint not null default([auth].[GetSystemId]()),
	[IsSystem] bit not null default(0),
	[ExternalProviderName] varchar(256) null,
	[FirstName] nvarchar(256) null,
	[LastName] nvarchar(256) null,
	[DisplayName] nvarchar(512) null,
	constraint PK_ApiUsers_ID primary key ([Id]),
	constraint UN_ApiUsers_Username unique ([Username]),
	constraint UN_ApiUsers_SystemId unique ([SystemId]),
	constraint FK_ApiUsers_CreatedByClientId foreign key ([CreatedByClientId]) references [auth].[ApiClients]([Id]),
	constraint FK_ApiUsers_CreatedByUserId foreign key ([CreatedByUserId]) references [auth].[ApiUsers]([Id]),
	constraint FK_ApiUsers_UpdatedByClientId foreign key ([UpdatedByClientId]) references [auth].[ApiClients]([Id]),
	constraint FK_ApiUsers_UpdatedByUserId foreign key ([UpdatedByUserId]) references [auth].[ApiUsers]([Id])
)
