CREATE TABLE [core].[Fields]
(
	[Id] INT NOT NULL PRIMARY KEY identity(100000,1),
	[TableName] varchar(64) not null,
	[Name] varchar(64) not null,
	[Title] varchar(64) not null,
	[Type] int not null,
	[IsHidden] bit not null default(0),
	[IsDeleted] bit not null default(0),
	[IsSystem] bit  not null default(0),
	[IsAutoGenerated] bit  not null default(0),
	[ShowInUi] bit  not null default(1),
	[UiIndex] int  not null default(0),
	[SqlDataType] varchar(64) not null,
	--[InternalName] varchar(64) not null,
	CONSTRAINT UniqueTableNameFieldName UNIQUE NONCLUSTERED ([TableName],[Name])
)
